application: eko-hub
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /docs/pic_firmware
  static_dir: p24fw_docs
  
- url: .*
  script: main.py

builtins:
- datastore_admin: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
#- ^(.*/)?Crypto